"""NLP vocabulary constants — extracted from nlp_engine.py.

Provides:
  TECH_SKILLS_VOCAB          — curated ~150-term tech/business skills set
  _AMBIGUOUS_SINGLE_WORDS    — terms that need word-boundary context matching
  _EMPLOYER_KEYWORD_BLOCKLIST — employer-description terms excluded from scoring
"""

# Curated tech-skills vocabulary (~150 common terms and multi-word phrases)
TECH_SKILLS_VOCAB = {
    # Programming languages
    "python",
    "java",
    "javascript",
    "typescript",
    "c++",
    "c#",
    "rust",
    "swift",
    "kotlin",
    "scala",
    "ruby",
    "php",
    # Frameworks & libraries
    "react",
    "angular",
    "vue",
    "node.js",
    "express",
    "django",
    "flask",
    "spring boot",
    "fastapi",
    ".net",
    "next.js",
    "svelte",
    "tailwind css",
    # Data & ML
    "machine learning",
    "deep learning",
    "artificial intelligence",
    "data science",
    "data engineering",
    "data analytics",
    "natural language processing",
    "computer vision",
    "tensorflow",
    "pytorch",
    "scikit-learn",
    "pandas",
    "numpy",
    "large language models",
    "generative ai",
    "mlops",
    "feature engineering",
    "model training",
    "model deployment",
    "data modeling",
    # Cloud & infra
    "aws",
    "azure",
    "gcp",
    "google cloud",
    "docker",
    "kubernetes",
    "terraform",
    "jenkins",
    "ci/cd",
    "devops",
    "microservices",
    "serverless",
    "ansible",
    "infrastructure as code",
    "cloud architecture",
    "aws lambda",
    "azure devops",
    "github actions",
    "gitlab ci",
    "helm",
    "istio",
    "service mesh",
    # Databases
    "sql",
    "nosql",
    "postgresql",
    "mysql",
    "mongodb",
    "redis",
    "elasticsearch",
    "dynamodb",
    "oracle",
    "sql server",
    "snowflake",
    "databricks",
    "apache kafka",
    "apache spark",
    "data warehouse",
    "data lake",
    "data pipeline",
    # Data governance & compliance
    "data governance",
    "data quality",
    "data lineage",
    "data catalog",
    "master data management",
    "metadata management",
    "data classification",
    "gdpr",
    "hipaa",
    "sox compliance",
    "pci dss",
    "regulatory compliance",
    "information security",
    "access control",
    "identity management",
    "single sign-on",
    "oauth",
    "zero trust",
    # ETL & integration
    "etl pipeline",
    "data integration",
    "api integration",
    "system integration",
    "middleware",
    "enterprise service bus",
    "informatica",
    "talend",
    "mulesoft",
    "apache airflow",
    "apache nifi",
    "real-time streaming",
    # Methodologies
    "agile",
    "scrum",
    "kanban",
    "waterfall",
    "lean methodology",
    "six sigma",
    "safe framework",
    "design thinking",
    "test-driven development",
    "behavior-driven development",
    "continuous integration",
    "continuous delivery",
    # Architecture
    "enterprise architecture",
    "solution architecture",
    "system design",
    "api design",
    "rest",
    "graphql",
    "event-driven",
    "domain-driven design",
    "microservices architecture",
    "cloud-native",
    "twelve-factor app",
    "togaf",
    "archimate",
    "technical architecture",
    # Business & management
    "project management",
    "program management",
    "product management",
    "business analysis",
    "requirements gathering",
    "stakeholder management",
    "change management",
    "strategic planning",
    "digital transformation",
    "cloud migration",
    "data migration",
    "vendor management",
    "budget management",
    "resource planning",
    "risk management",
    "business process improvement",
    "process automation",
    "rpa",
    "cross-functional teams",
    "team leadership",
    "people management",
    # Visualization & BI
    "power bi",
    "tableau",
    "looker",
    "qlik",
    "business intelligence",
    "data visualization",
    "reporting",
    "dashboard development",
    # Testing & quality
    "test automation",
    "selenium",
    "cypress",
    "jest",
    "unit testing",
    "integration testing",
    "performance testing",
    "load testing",
    "quality assurance",
    "code review",
    # Security
    "cybersecurity",
    "penetration testing",
    "vulnerability assessment",
    "security architecture",
    "threat modeling",
    "siem",
    "soc",
    # Soft skills (enterprise-relevant)
    "technical writing",
    "presentation skills",
    "client engagement",
    "consulting",
    "mentoring",
    "coaching",
}

# Single-word terms that are ambiguous without context — only match as part of
# multi-word phrases or when they appear as standalone technical terms
_AMBIGUOUS_SINGLE_WORDS = {"go", "r", "lean"}

# Employer-description terms that should never appear as job-skill keywords.
# These phrases describe the employer or employment conditions, not the role's
# technical/professional requirements.
_EMPLOYER_KEYWORD_BLOCKLIST = frozenset({
    "company culture", "culture fit",
    "employee perk", "employee perks",
    "company benefit", "company benefits", "employee benefit", "employee benefits",
    "work life balance", "work-life balance",
    "competitive salary", "competitive compensation",
    "team building", "team event",
    "equal opportunity", "equal opportunity employer",
    "paid time off", "health insurance", "dental insurance", "vision insurance",
    "remote work", "hybrid work",
    "job requirement", "position requirement",
    "we offer", "we provide", "join our team", "join us",
    "applicant", "candidate",
})
