"""
Resume export to PDF and DOCX formats.
Generated by RTX 5090 (Qwen3-Coder-30B), validated and fixed by Expert AI.
"""

import re
from io import BytesIO

# Section headers to detect (case-insensitive)
SECTION_HEADERS = [
    "Summary",
    "Executive Summary",
    "Profile",
    "Experience",
    "Professional Experience",
    "Work Experience",
    "Skills",
    "Technical Skills",
    "Core Competencies",
    "Education",
    "Professional Highlights",
    "Key Accomplishments",
    "Certifications",
    "Endorsed Skills",
    "Professional Endorsements",
    "Additional Relevant Skills",
]

_HEADER_PATTERN = re.compile(
    r"^(?:#{1,4}\s*)?(?:\*{1,2})?\s*("
    + "|".join(re.escape(h) for h in SECTION_HEADERS)
    + r")\s*(?:\*{1,2})?:?\s*$",
    re.IGNORECASE,
)


def _strip_markdown(text):
    """Remove markdown bold/italic markers and header hashes."""
    text = re.sub(r"\*{1,2}(.+?)\*{1,2}", r"\1", text)
    text = re.sub(r"^#{1,4}\s*", "", text)
    text = text.replace("---", "").strip()
    return text


def _parse_resume_sections(text):
    """Parse resume text into (header_lines, [(section_title, [content_lines])])."""
    lines = text.strip().split("\n")
    header_lines = []
    sections = []
    current_section = None
    current_content = []

    # First 1-5 lines before first section = name/contact info
    i = 0
    for i, line in enumerate(lines):  # noqa: B007
        stripped = line.strip()
        if not stripped or stripped == "---":
            if header_lines:
                header_lines.append("")
            continue
        if _HEADER_PATTERN.match(stripped):
            break
        header_lines.append(_strip_markdown(stripped))
    else:
        i = len(lines)

    # Process remaining lines into sections
    for j in range(i, len(lines)):
        line = lines[j]
        stripped = line.strip()

        match = _HEADER_PATTERN.match(stripped)
        if match:
            if current_section:
                sections.append((current_section, current_content))
            current_section = match.group(1).strip()
            current_content = []
        elif not stripped or stripped == "---":
            if current_content and current_content[-1] != "":
                current_content.append("")
        else:
            current_content.append(_strip_markdown(stripped))

    if current_section:
        sections.append((current_section, current_content))

    # Clean trailing empty lines from each section
    for i, (title, content) in enumerate(sections):
        while content and content[-1] == "":
            content.pop()
        sections[i] = (title, content)

    return header_lines, sections


def export_resume_pdf(text):
    """Convert resume text to a professionally formatted PDF. Returns BytesIO."""
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=inch,
        rightMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
    )

    styles = getSampleStyleSheet()

    name_style = ParagraphStyle(
        "Name", parent=styles["Normal"], fontSize=16, alignment=TA_CENTER, spaceAfter=2
    )
    contact_style = ParagraphStyle(
        "Contact", parent=styles["Normal"], fontSize=10, alignment=TA_CENTER, spaceAfter=4
    )
    section_style = ParagraphStyle(
        "SectionHeader",
        parent=styles["Normal"],
        fontSize=13,
        leading=16,
        spaceBefore=12,
        spaceAfter=6,
        textColor="black",
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"], fontSize=11, leading=14, spaceAfter=3, alignment=TA_LEFT
    )
    bullet_style = ParagraphStyle(
        "Bullet",
        parent=body_style,
        leftIndent=18,
        bulletIndent=6,
        spaceAfter=2,
    )

    header_lines, sections = _parse_resume_sections(text)

    story = []

    # Name/contact header
    for k, line in enumerate(header_lines):
        if not line:
            continue
        if k == 0:
            story.append(Paragraph(line, name_style))
        else:
            story.append(Paragraph(line, contact_style))

    if header_lines:
        story.append(Spacer(1, 10))

    # Sections
    for title, content in sections:
        story.append(Paragraph(f"<b>{title.upper()}</b>", section_style))
        for item in content:
            if not item:
                story.append(Spacer(1, 4))
            elif item.startswith("- ") or item.startswith("* "):
                bullet_text = item[2:].strip()
                story.append(Paragraph(f"\u2022  {bullet_text}", bullet_style))
            else:
                story.append(Paragraph(item, body_style))
        story.append(Spacer(1, 6))

    # Page numbers
    def _add_page_number(canvas, doc):
        page_num = canvas.getPageNumber()
        canvas.saveState()
        canvas.setFont("Helvetica", 9)
        canvas.drawCentredString(letter[0] / 2, 0.5 * inch, f"Page {page_num}")
        canvas.restoreState()

    doc.build(story, onFirstPage=_add_page_number, onLaterPages=_add_page_number)
    buffer.seek(0)
    return buffer


def export_resume_docx(text):
    """Convert resume text to a professionally formatted DOCX. Returns BytesIO."""
    from docx import Document
    from docx.shared import Pt

    buffer = BytesIO()
    doc = Document()

    # Set default font
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)

    header_lines, sections = _parse_resume_sections(text)

    # Name/contact header
    for k, line in enumerate(header_lines):
        if not line:
            continue
        if k == 0:
            p = doc.add_paragraph()
            run = p.add_run(line)
            run.bold = True
            run.font.size = Pt(16)
        else:
            doc.add_paragraph(line)

    # Sections
    for title, content in sections:
        doc.add_heading(title, level=2)
        for item in content:
            if not item:
                continue
            elif item.startswith("- ") or item.startswith("* "):
                doc.add_paragraph(item[2:].strip(), style="List Bullet")
            else:
                doc.add_paragraph(item)

    doc.save(buffer)
    buffer.seek(0)
    return buffer
