"""Error handling and edge case tests — negative/defensive paths.

20 tests covering upload errors, optimization errors, auth errors,
agent route errors, and data validation errors. No LLM required.

Generated by RTX 5090 (Qwen3-Coder-30B-AWQ), validated and corrected by Expert AI.
"""

import io
import os
import sys

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if BACKEND_DIR not in sys.path:
    sys.path.insert(0, BACKEND_DIR)

from test_helpers import JD_TEXT, RESUME_TEXT, query_db, upload_jd, upload_resume  # noqa: E402

# ---------------------------------------------------------------------------
# Upload Errors
# ---------------------------------------------------------------------------


class TestUploadErrors:
    """Error handling during file uploads."""

    def test_upload_resume_wrong_content_type(self, client, auth_headers):
        """POST resume without multipart form data returns error."""
        resp = client.post(
            "/api/resume/upload",
            headers=auth_headers,
            json={"file": "not-a-file"},
        )
        assert resp.status_code in (400, 415, 422)
        data = resp.get_json()
        assert data is not None
        assert "error" in data or "message" in data or "msg" in data

    def test_upload_resume_no_file_field(self, client, auth_headers):
        """POST resume with empty multipart but no file field."""
        resp = client.post(
            "/api/resume/upload",
            headers={"Authorization": auth_headers["Authorization"]},
            data={},
            content_type="multipart/form-data",
        )
        assert resp.status_code in (400, 422)
        data = resp.get_json() or {}
        assert isinstance(data, dict)

    def test_upload_resume_empty_file(self, client, auth_headers):
        """POST resume with an empty file body."""
        resp = client.post(
            "/api/resume/upload",
            headers={"Authorization": auth_headers["Authorization"]},
            data={"file": (io.BytesIO(b""), "empty.txt")},
            content_type="multipart/form-data",
        )
        # Should fail or return low-quality result
        assert resp.status_code in (201, 400, 422)
        if resp.status_code == 201:
            data = resp.get_json()
            assert "resume_id" in data  # Even empty files get an ID
        # DB: verify no duplicate resumes from empty upload
        rows = query_db("SELECT COUNT(*) as cnt FROM resumes WHERE user_id = 1")
        assert rows[0]["cnt"] <= 1

    def test_upload_jd_empty_text(self, client, auth_headers):
        """POST JD with empty text returns 400."""
        resp = client.post(
            "/api/job-description/upload",
            headers=auth_headers,
            json={"job_text": ""},
        )
        assert resp.status_code == 400
        data = resp.get_json()
        assert isinstance(data, dict)
        assert "error" in data or "message" in data

    def test_upload_jd_very_short(self, client, auth_headers):
        """POST JD with very short text (<50 chars) returns 400."""
        resp = client.post(
            "/api/job-description/upload",
            headers=auth_headers,
            json={"job_text": "Short JD."},
        )
        assert resp.status_code == 400
        data = resp.get_json()
        assert isinstance(data, dict)
        assert "error" in data


# ---------------------------------------------------------------------------
# Optimization Errors
# ---------------------------------------------------------------------------


class TestOptimizationErrors:
    """Error handling during resume optimization."""

    def test_optimize_nonexistent_resume(self, client, auth_headers):
        """Optimizing a resume that doesn't exist returns 404."""
        upload_jd(client, auth_headers)  # need JD present
        resp = client.post("/api/optimize-resume/99999", headers=auth_headers, json={})
        assert resp.status_code in (400, 404)
        data = resp.get_json()
        assert isinstance(data, dict)
        # DB: confirm resume 99999 doesn't exist
        rows = query_db("SELECT id FROM resumes WHERE id = 99999")
        assert len(rows) == 0

    def test_optimize_without_jd(self, client, auth_headers):
        """Optimizing before uploading a JD returns error."""
        rid = upload_resume(client, auth_headers)
        resp = client.post(f"/api/optimize-resume/{rid}", headers=auth_headers, json={})
        # No JD uploaded yet — should fail
        assert resp.status_code in (400, 404, 200)
        # If 200, verify result still has score structure
        if resp.status_code == 200:
            data = resp.get_json()
            assert "score" in data
        # DB: resume exists
        rows = query_db("SELECT id FROM resumes WHERE user_id = 1")
        assert len(rows) >= 1

    def test_optimize_other_users_resume(self, client, auth_headers, second_user_headers):
        """User cannot optimize another user's resume."""
        rid = upload_resume(client, auth_headers)
        upload_jd(client, second_user_headers)  # second user has JD
        resp = client.post(f"/api/optimize-resume/{rid}", headers=second_user_headers, json={})
        assert resp.status_code in (400, 403, 404)
        data = resp.get_json()
        assert isinstance(data, dict)
        # DB: resume belongs to user 1
        rows = query_db("SELECT user_id FROM resumes WHERE id = ?", (rid,))
        assert len(rows) == 1
        assert rows[0]["user_id"] == 1

    def test_double_optimize_idempotent(self, client, auth_headers):
        """Double-optimizing the same resume doesn't crash."""
        rid = upload_resume(client, auth_headers)
        upload_jd(client, auth_headers)
        resp1 = client.post(f"/api/optimize-resume/{rid}", headers=auth_headers, json={})
        resp2 = client.post(f"/api/optimize-resume/{rid}", headers=auth_headers, json={})
        assert resp1.status_code == 200
        assert resp2.status_code == 200
        data1 = resp1.get_json()
        data2 = resp2.get_json()
        # Both should have valid ATS score (key is ats_compliance_score)
        score_key = "score" if "score" in data1 else "ats_compliance_score"
        assert score_key in data1
        assert score_key in data2
        # DB: still only one resume
        rows = query_db("SELECT id FROM resumes WHERE id = ?", (rid,))
        assert len(rows) == 1


# ---------------------------------------------------------------------------
# Auth Errors
# ---------------------------------------------------------------------------


class TestAuthErrors:
    """Authentication error handling."""

    def test_no_auth_header(self, client):
        """Accessing protected endpoint without auth header returns 401."""
        resp = client.post("/api/resume/upload", data={})
        assert resp.status_code in (401, 403)
        data = resp.get_json() or {}
        assert isinstance(data, dict)

    def test_invalid_jwt_token(self, client):
        """Invalid JWT token returns 401."""
        resp = client.post(
            "/api/resume/upload",
            headers={"Authorization": "Bearer not-a-valid-token"},
            data={},
        )
        assert resp.status_code in (401, 403, 422)
        data = resp.get_json() or {}
        assert isinstance(data, dict)

    def test_malformed_auth_header(self, client):
        """Malformed Authorization header returns 401."""
        resp = client.post(
            "/api/resume/upload",
            headers={"Authorization": "garbage"},
            data={},
        )
        assert resp.status_code in (401, 403, 422)
        data = resp.get_json() or {}
        assert isinstance(data, dict)


# ---------------------------------------------------------------------------
# Agent Route Errors
# ---------------------------------------------------------------------------


class TestAgentRouteErrors:
    """Error handling in agent routes."""

    def test_scout_posting_missing_required_fields(self, client, auth_headers):
        """Creating posting without required fields returns 400."""
        resp = client.post(
            "/api/agents/scout/postings",
            headers={"user-id": "1", "Content-Type": "application/json"},
            json={},
        )
        assert resp.status_code in (400, 422)
        data = resp.get_json()
        assert isinstance(data, dict)

    def test_scout_posting_nonexistent_id(self, client, auth_headers):
        """GET nonexistent posting returns 404."""
        resp = client.get(
            "/api/agents/scout/postings/nonexistent-uuid-12345",
            headers={"user-id": "1", "Content-Type": "application/json"},
        )
        assert resp.status_code == 404
        data = resp.get_json()
        assert isinstance(data, dict)

    def test_coach_answer_missing_session_id(self, client, auth_headers):
        """POST answer without session_id returns 400."""
        resp = client.post(
            "/api/agents/coach/answer",
            headers=auth_headers,
            json={"answer": "some answer"},
        )
        assert resp.status_code == 400
        data = resp.get_json()
        assert "error" in data

    def test_advisor_roadmap_missing_target_role(self, client, auth_headers):
        """POST skills-roadmap without target_role returns 400."""
        resp = client.post(
            "/api/agents/advisor/skills-roadmap",
            headers=auth_headers,
            json={},
        )
        assert resp.status_code == 400
        data = resp.get_json()
        assert "error" in data


# ---------------------------------------------------------------------------
# Data Validation Errors
# ---------------------------------------------------------------------------


class TestDataValidationErrors:
    """Input validation error handling."""

    def test_register_missing_email(self, client):
        """Registration without email returns 400."""
        resp = client.post(
            "/api/register",
            json={"password": "ValidPass123!"},
        )
        assert resp.status_code == 400
        data = resp.get_json()
        assert "error" in data

    def test_register_missing_password(self, client):
        """Registration without password returns 400."""
        resp = client.post(
            "/api/register",
            json={"email": "valid@test.com"},
        )
        assert resp.status_code == 400
        data = resp.get_json()
        assert "error" in data

    def test_register_invalid_email_format(self, client):
        """Registration with invalid email format returns 400."""
        resp = client.post(
            "/api/register",
            json={"email": "not-an-email", "password": "ValidPass123!"},
        )
        assert resp.status_code == 400
        data = resp.get_json()
        assert "error" in data

    def test_register_short_password(self, client):
        """Registration with too-short password returns 400."""
        resp = client.post(
            "/api/register",
            json={"email": "shortpw@test.com", "password": "abc"},
        )
        assert resp.status_code == 400
        data = resp.get_json()
        assert "error" in data

    def test_login_wrong_password(self, client):
        """Login with wrong password returns 401."""
        client.post(
            "/api/register",
            json={"email": "wrongpw@test.com", "password": "CorrectPass1!"},
        )
        resp = client.post(
            "/api/login",
            json={"email": "wrongpw@test.com", "password": "WrongPassword!"},
        )
        assert resp.status_code == 401
        data = resp.get_json()
        assert isinstance(data, dict)
        # DB: user still exists after failed login
        rows = query_db("SELECT id FROM users WHERE email = 'wrongpw@test.com'")
        assert len(rows) == 1

    def test_register_duplicate_email(self, client):
        """Duplicate email registration returns 400 or 409."""
        client.post(
            "/api/register",
            json={"email": "dupe@test.com", "password": "ValidPass1!"},
        )
        resp = client.post(
            "/api/register",
            json={"email": "dupe@test.com", "password": "ValidPass1!"},
        )
        assert resp.status_code in (400, 409)
        data = resp.get_json()
        assert isinstance(data, dict)
        # DB: only one user with this email
        rows = query_db("SELECT id FROM users WHERE email = 'dupe@test.com'")
        assert len(rows) == 1
