"""End-to-end tests for agent system — Resume Tailor, Cover Letter,
Interview Coach, Career Advisor. All require RTX 5090 LLM.

Generated by RTX 5090 (Qwen3-Coder-30B-AWQ), validated by Expert AI.
"""

import os
import sys

import pytest

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if BACKEND_DIR not in sys.path:
    sys.path.insert(0, BACKEND_DIR)

from test_helpers import LINKEDIN_PROFILE, RESUME_TEXT, query_db  # noqa: E402

pytestmark = pytest.mark.llm_required


@pytest.fixture()
def agent_setup(client, auth_headers, resume_and_jd, posting_id):
    """Set up LinkedIn profile + resume + JD + posting for agent tests."""
    client.post("/api/import/linkedin", headers=auth_headers, json={})
    rid, _ = resume_and_jd

    # Tailor agent queries resume_versions (not resumes), so seed one
    from models import ResumeVersion

    ResumeVersion.create(
        user_id=1,
        source="upload",
        file_name="resume.txt",
        parsed_text=RESUME_TEXT,
    )

    return {"resume_id": rid, "posting_id": posting_id}


# ---------------------------------------------------------------------------
# Resume Tailor
# ---------------------------------------------------------------------------


class TestResumeTailor:
    """E2E tests for Resume Tailor agent."""

    def test_tailor_resume_for_posting(self, client, auth_headers, require_harness, agent_setup):
        """Tailoring resume produces version with score."""
        pid = agent_setup["posting_id"]
        resp = client.post(f"/api/agents/tailor/{pid}", headers=auth_headers, json={})
        assert resp.status_code == 200
        data = resp.get_json()
        assert (
            "version_id" in data or "optimized_text" in data
        ), f"Expected version_id or optimized_text, got keys: {list(data.keys())}"
        # Score should be present and numeric
        if "score" in data:
            assert isinstance(data["score"], (int, float))
            assert 0 <= data["score"] <= 100
        # DB: verify agent run logged
        runs = query_db(
            "SELECT agent_type, status FROM agent_runs WHERE user_id = 1 AND agent_type = 'resume_tailor'"
        )
        assert len(runs) >= 1
        assert runs[-1]["status"] in ("completed", "running")

    def test_retrieve_tailored_resume(self, client, auth_headers, require_harness, agent_setup):
        """After tailoring, GET retrieves the tailored version."""
        pid = agent_setup["posting_id"]
        client.post(f"/api/agents/tailor/{pid}", headers=auth_headers, json={})
        resp = client.get(f"/api/agents/tailor/{pid}", headers=auth_headers)
        assert resp.status_code == 200
        data = resp.get_json()
        assert isinstance(data, dict)
        # Should have text content
        text_fields = [k for k in data if "text" in k.lower()]
        assert (
            len(text_fields) >= 1 or "optimized_text" in data or "parsed_text" in data
        ), f"No text field in tailored resume: {list(data.keys())}"

    def test_tailor_nonexistent_posting(self, client, auth_headers, require_harness, agent_setup):
        """Tailoring for a nonexistent posting returns error."""
        resp = client.post("/api/agents/tailor/nonexistent-id", headers=auth_headers, json={})
        assert resp.status_code in (400, 404)


# ---------------------------------------------------------------------------
# Cover Letter
# ---------------------------------------------------------------------------


class TestCoverLetter:
    """E2E tests for Cover Letter agent."""

    def test_generate_cover_letter(self, client, auth_headers, require_harness, agent_setup):
        """Generating a cover letter returns structured content."""
        pid = agent_setup["posting_id"]
        resp = client.post(f"/api/agents/cover-letter/{pid}", headers=auth_headers, json={})
        assert resp.status_code == 201
        data = resp.get_json()
        assert "id" in data, f"Expected 'id' in response, got: {list(data.keys())}"
        assert isinstance(data["id"], str)
        # Should have letter structure
        for field in ("body",):
            assert field in data, f"Missing field '{field}' in cover letter"
        assert len(data.get("body", "")) > 20, "Cover letter body too short"
        # DB: verify cover letter persisted
        letters = query_db("SELECT id, posting_id FROM cover_letters WHERE user_id = 1")
        assert len(letters) >= 1

    def test_retrieve_cover_letter_by_posting(
        self, client, auth_headers, require_harness, agent_setup
    ):
        """GET retrieves cover letter for a posting."""
        pid = agent_setup["posting_id"]
        client.post(f"/api/agents/cover-letter/{pid}", headers=auth_headers, json={})
        resp = client.get(f"/api/agents/cover-letter/{pid}", headers=auth_headers)
        assert resp.status_code == 200
        data = resp.get_json()
        assert "body" in data
        assert data["body"] != ""

    def test_retrieve_cover_letter_by_id(self, client, auth_headers, require_harness, agent_setup):
        """GET retrieves cover letter by ID."""
        pid = agent_setup["posting_id"]
        gen = client.post(f"/api/agents/cover-letter/{pid}", headers=auth_headers, json={})
        letter_id = gen.get_json()["id"]
        resp = client.get(f"/api/agents/cover-letters/{letter_id}", headers=auth_headers)
        assert resp.status_code == 200
        data = resp.get_json()
        assert "body" in data
        assert data["tone"] != ""

    def test_update_cover_letter(self, client, auth_headers, require_harness, agent_setup):
        """PUT updates cover letter fields."""
        pid = agent_setup["posting_id"]
        gen = client.post(f"/api/agents/cover-letter/{pid}", headers=auth_headers, json={})
        letter_id = gen.get_json()["id"]
        updates = {"subject": "Updated Subject Line", "tone": "formal"}
        resp = client.put(
            f"/api/agents/cover-letters/{letter_id}",
            headers=auth_headers,
            json=updates,
        )
        assert resp.status_code == 200
        data = resp.get_json()
        assert data.get("subject") == "Updated Subject Line"

    def test_delete_cover_letter(self, client, auth_headers, require_harness, agent_setup):
        """DELETE removes cover letter; subsequent GET returns 404."""
        pid = agent_setup["posting_id"]
        gen = client.post(f"/api/agents/cover-letter/{pid}", headers=auth_headers, json={})
        letter_id = gen.get_json()["id"]
        resp = client.delete(f"/api/agents/cover-letters/{letter_id}", headers=auth_headers)
        assert resp.status_code == 200
        # Verify deletion
        resp2 = client.get(f"/api/agents/cover-letters/{letter_id}", headers=auth_headers)
        assert resp2.status_code == 404
        # DB: verify cover letter deleted
        rows = query_db("SELECT id FROM cover_letters WHERE id = ?", (letter_id,))
        assert len(rows) == 0

    def test_regenerate_cover_letter(self, client, auth_headers, require_harness, agent_setup):
        """Regenerate with feedback produces updated letter."""
        pid = agent_setup["posting_id"]
        gen = client.post(f"/api/agents/cover-letter/{pid}", headers=auth_headers, json={})
        letter_id = gen.get_json()["id"]
        resp = client.post(
            f"/api/agents/cover-letters/{letter_id}/regenerate",
            headers=auth_headers,
            json={"feedback": "make it more formal and concise"},
        )
        assert resp.status_code == 200
        data = resp.get_json()
        assert "body" in data
        assert data["body"] != ""


# ---------------------------------------------------------------------------
# Interview Coach
# ---------------------------------------------------------------------------


class TestInterviewCoach:
    """E2E tests for Interview Coach agent."""

    def test_start_mock_interview(self, client, auth_headers, require_harness, agent_setup):
        """Starting a mock interview returns session with opening."""
        pid = agent_setup["posting_id"]
        resp = client.post(
            "/api/agents/coach/start",
            headers=auth_headers,
            json={"posting_id": pid, "persona": "hiring_manager", "question_count": 2},
        )
        assert resp.status_code == 201
        data = resp.get_json()
        assert "session_id" in data, f"Expected session_id, got: {list(data.keys())}"
        assert isinstance(data["session_id"], str)
        # DB: verify interview session created
        sessions = query_db("SELECT id, persona FROM interview_coach_sessions WHERE user_id = 1")
        assert len(sessions) >= 1

    def test_answer_question_returns_score(
        self, client, auth_headers, require_harness, agent_setup
    ):
        """Answering a question returns score and feedback."""
        pid = agent_setup["posting_id"]
        start = client.post(
            "/api/agents/coach/start",
            headers=auth_headers,
            json={"posting_id": pid, "persona": "technical", "question_count": 2},
        )
        session_id = start.get_json()["session_id"]
        resp = client.post(
            "/api/agents/coach/answer",
            headers=auth_headers,
            json={
                "session_id": session_id,
                "answer": "I have extensive experience with Python, AWS, and microservices "
                "architecture. At my previous role, I designed a cloud-native platform "
                "serving 30M+ members with 99.99% uptime.",
            },
        )
        assert resp.status_code == 200
        data = resp.get_json()
        # Should have scoring data
        assert (
            "score" in data or "scores" in data
        ), f"Expected score/scores in response: {list(data.keys())}"
        # DB: verify answer message stored
        msgs = query_db(
            "SELECT role FROM interview_coach_messages WHERE session_id = ?", (session_id,)
        )
        assert len(msgs) >= 1

    def test_get_session_details(self, client, auth_headers, require_harness, agent_setup):
        """GET retrieves session with metadata."""
        pid = agent_setup["posting_id"]
        start = client.post(
            "/api/agents/coach/start",
            headers=auth_headers,
            json={"posting_id": pid, "persona": "hr_recruiter", "question_count": 1},
        )
        session_id = start.get_json()["session_id"]
        resp = client.get(f"/api/agents/coach/{session_id}", headers=auth_headers)
        assert resp.status_code == 200
        data = resp.get_json()
        assert isinstance(data, dict)
        # Session should have basic metadata
        assert "persona" in data or "session_id" in data or "id" in data

    def test_list_sessions(self, client, auth_headers, require_harness, agent_setup):
        """List sessions returns array with count."""
        # Create a session first
        pid = agent_setup["posting_id"]
        client.post(
            "/api/agents/coach/start",
            headers=auth_headers,
            json={"posting_id": pid, "persona": "hiring_manager", "question_count": 1},
        )
        resp = client.get("/api/agents/coach/sessions", headers=auth_headers)
        assert resp.status_code == 200
        data = resp.get_json()
        assert "sessions" in data
        assert isinstance(data["sessions"], list)
        assert data["count"] >= 1

    def test_complete_interview_flow(self, client, auth_headers, require_harness, agent_setup):
        """Full flow: start → answer all questions → get assessment."""
        pid = agent_setup["posting_id"]
        start = client.post(
            "/api/agents/coach/start",
            headers=auth_headers,
            json={"posting_id": pid, "persona": "hiring_manager", "question_count": 1},
        )
        session_id = start.get_json()["session_id"]

        # Answer the single question
        client.post(
            "/api/agents/coach/answer",
            headers=auth_headers,
            json={
                "session_id": session_id,
                "answer": "I led a team of 12 engineers to migrate our monolithic "
                "Java application to Python/FastAPI microservices, reducing "
                "deployment time from 2 weeks to 2 hours.",
            },
        )

        # Get assessment
        resp = client.get(f"/api/agents/coach/{session_id}/assessment", headers=auth_headers)
        # May return 200 (assessment ready) or 400 (not complete yet)
        assert resp.status_code in (200, 400)
        data = resp.get_json()
        assert isinstance(data, dict)


# ---------------------------------------------------------------------------
# Career Advisor
# ---------------------------------------------------------------------------


class TestCareerAdvisor:
    """E2E tests for Career Advisor agent."""

    def test_analyze_career(self, client, auth_headers, require_harness, agent_setup):
        """Career analysis returns trajectory and strengths."""
        resp = client.post("/api/agents/advisor/analyze", headers=auth_headers, json={})
        assert resp.status_code == 200
        data = resp.get_json()
        # LLM returns structured career analysis
        assert isinstance(data, dict)
        assert "error" not in data, f"Got error: {data.get('error')}"
        # Should have some career-related keys
        career_keys = {
            "career_trajectory",
            "strengths",
            "growth_areas",
            "market_alignment",
            "recommended_learning",
            "role_recommendations",
        }
        found = career_keys & set(data.keys())
        assert len(found) >= 2, f"Expected ≥2 career analysis keys, got: {list(data.keys())}"
        # DB: verify career analysis persisted
        analyses = query_db("SELECT analysis_type FROM career_analyses WHERE user_id = 1")
        assert len(analyses) >= 1

    def test_skills_roadmap(self, client, auth_headers, require_harness, agent_setup):
        """Skills roadmap returns phases and quick wins."""
        resp = client.post(
            "/api/agents/advisor/skills-roadmap",
            headers=auth_headers,
            json={"target_role": "CTO"},
        )
        assert resp.status_code == 200
        data = resp.get_json()
        assert isinstance(data, dict)
        assert "error" not in data, f"Got error: {data.get('error')}"
        # Should have roadmap structure
        roadmap_keys = {
            "phases",
            "quick_wins",
            "key_gap",
            "target_role",
            "current_readiness",
            "timeline_months",
        }
        found = roadmap_keys & set(data.keys())
        assert len(found) >= 2, f"Expected ≥2 roadmap keys, got: {list(data.keys())}"

    def test_skills_roadmap_requires_target_role(
        self, client, auth_headers, require_harness, agent_setup
    ):
        """Skills roadmap without target_role returns 400."""
        resp = client.post(
            "/api/agents/advisor/skills-roadmap",
            headers=auth_headers,
            json={},
        )
        assert resp.status_code == 400

    def test_role_recommendations(self, client, auth_headers, require_harness, agent_setup):
        """Role recommendations returns list of roles with scores."""
        resp = client.post(
            "/api/agents/advisor/role-recommendations",
            headers=auth_headers,
            json={},
        )
        assert resp.status_code == 200
        data = resp.get_json()
        assert isinstance(data, dict)
        assert "error" not in data, f"Got error: {data.get('error')}"
        # Should have recommendations
        recs = data.get("recommendations", data.get("roles", []))
        if isinstance(recs, list) and len(recs) > 0:
            rec = recs[0]
            assert "title" in rec, f"Recommendation missing 'title': {list(rec.keys())}"

    def test_history_after_analysis(self, client, auth_headers, require_harness, agent_setup):
        """History endpoint returns past analyses."""
        # Run an analysis first
        client.post("/api/agents/advisor/analyze", headers=auth_headers, json={})
        resp = client.get("/api/agents/advisor/history", headers=auth_headers)
        assert resp.status_code == 200
        data = resp.get_json()
        assert "analyses" in data
        assert data["analyses"] != []
        assert len(data["analyses"]) >= 1, "Expected ≥1 analysis in history after running one"
        # DB: verify analyses stored
        rows = query_db("SELECT id, analysis_type FROM career_analyses WHERE user_id = 1")
        assert len(rows) >= 1

    def test_history_filter_by_type(self, client, auth_headers, require_harness, agent_setup):
        """History can be filtered by analysis_type."""
        client.post("/api/agents/advisor/analyze", headers=auth_headers, json={})
        resp = client.get(
            "/api/agents/advisor/history?type=career_analysis",
            headers=auth_headers,
        )
        assert resp.status_code == 200
        data = resp.get_json()
        assert "analyses" in data
        assert isinstance(data["analyses"], list)
